name: Daniel Rojas
favicon: null
layout_spectrum: 0.69796
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B0C0C8'
    - '#817304'
    - '#905860'
    - '#F8E020'
    - '#F0E050'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
