name: Daniel Rojas
favicon: null
layout_spectrum: 0.69629
typography_spectrum: 0.65904
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121212'
    - '#454545'
    - '#e0e0e0'
    - '#888888'
    - '#b0b0b0'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
