name: Daniel Rojas
favicon: null
layout_spectrum: 0.04495664732530713
typography_spectrum: 0.605620049405843
title: Mi first web on the grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.25241723423823714
  lightness: 0.47303096135146916
  saturation: 0.6098028689157218
  rhythmicContrast: 0.0483289728872478
purpose: []
